<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net20;netstandard1.0;net9.0</TargetFrameworks>
    <LangVersion>2</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Disable "Targeting .NET Standard prior to 2.0 is no longer recommended." warning -->
    <NoWarn>$(NoWarn);NETSDK1215</NoWarn>
  </PropertyGroup>

  <!-- .NET Framework v2.0 compatible CI builds -->
  <ItemGroup Condition="'$(TargetFramework)' == 'net20'">
    <PackageReference PrivateAssets="All" IncludeAssets="runtime; build; native; contentfiles; analyzers" Include="Microsoft.NETFramework.ReferenceAssemblies.net20" Version="1.0.3" />
  </ItemGroup>

</Project>
